name: Simple Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Python Script
        run: python script.py

