name: Python Script Workflow

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: windows-latest  # Using Windows runner for debugging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug: List Files
        run: dir  # Show all files in the repository

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Run Python Script
        run: python script.py
